# +=======================================================================+
# |    Copyright (c) 2006 Oracle Argentina, Buenos Aires                  |
# |                         All rights reserved.                          |
# +=======================================================================+
# | FILENAME                                                              |
# |    xxdownload.sh                                                      |
# |                                                                       |
# | DESCRIPTION                                                           |
# |    Script de Download                                                 |
# |                                                                       |
# | PRODUCT                                                               |
# |    Oracle Financials                                                  |
# |                                                                       |
# | HISTORY                                                               |
# |    10-DEC-2008 1.0      Generic          Created                      |
# |                                                                       |
# | NOTES                                                                 |
# |                                                                       |
# +=======================================================================+
echo '====================================================================='
echo 'Script xxdownload.sh'
echo '====================================================================='

echo 'Please, enter the APPS USER: '
read APPS_USER 
echo 'Please, enter the APPS PASSWORD: '
read APPS_PWD 
echo 'Please, enter the DATABASE name: '
read BASE 

echo 'Conecting with ' $APPS_USER
echo 'Base ' $BASE 
echo '====================================================================='
echo 'Begin Objects Download.'
echo '====================================================================='

echo 'Bajando objeto XX_XX_UTIL'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxcustom.lct XX_CUS_XX_UTIL_0.ldt XX_CUSTOM_HEADERS CUSTOM_CODE=XX_UTIL

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_110.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS_APPL'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_APPL_112.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS_APPL

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS_EXCEP'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_EXCEP_114.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS_EXCEP

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS_LEVEL1'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_LEVEL1_292.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS_LEVEL1

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS_LEVEL2'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_LEVEL2_292.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS_LEVEL2

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS_LEVEL3'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_LEVEL3_292.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS_LEVEL3

echo 'Bajando objeto XX_XX_CTRL_CUSTOMS_RESULT'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CTRL_CUSTOMS_RESULT_212.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CTRL_CUSTOMS_RESULT

echo 'Bajando objeto XX_XX_CUSTOM_HEADER'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_CUSTOM_HEADER_290.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_CUSTOM_HEADER

echo 'Bajando objeto XX_XX_DOC_CUSTOMS_FORMATS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct XX_VLS_XX_DOC_CUSTOMS_FORMATS_294.ldt VALUE_SET FLEX_VALUE_SET_NAME=XX_DOC_CUSTOMS_FORMATS

echo 'Bajando objeto XX_XX_DOC_CUSTOMS_FORMATS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct XX_LKP_XX_DOC_CUSTOMS_FORMATS_102.ldt FND_LOOKUP_TYPE LOOKUP_TYPE=XX_DOC_CUSTOMS_FORMATS

echo 'Bajando objeto XX_XX_MAPPING_TYPES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct XX_LKP_XX_MAPPING_TYPES_100.ldt FND_LOOKUP_TYPE LOOKUP_TYPE=XX_MAPPING_TYPES

echo 'Bajando objeto XX_XX_CONTROL_CUSTOMS_TEMP'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_CONTROL_CUSTOMS_TEMP_330.ldt FND_TABLE TABLE_NAME=XX_CONTROL_CUSTOMS_TEMP

echo 'Bajando objeto XX_XX_CUSTOM_DETAILS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_CUSTOM_DETAILS_342.ldt FND_TABLE TABLE_NAME=XX_CUSTOM_DETAILS

echo 'Bajando objeto XX_XX_CUSTOM_DRIVERS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_CUSTOM_DRIVERS_338.ldt FND_TABLE TABLE_NAME=XX_CUSTOM_DRIVERS

echo 'Bajando objeto XX_XX_CUSTOM_EXECS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_CUSTOM_EXECS_336.ldt FND_TABLE TABLE_NAME=XX_CUSTOM_EXECS

echo 'Bajando objeto XX_XX_CUSTOM_HEADERS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_CUSTOM_HEADERS_334.ldt FND_TABLE TABLE_NAME=XX_CUSTOM_HEADERS

echo 'Bajando objeto XX_XX_CUSTOM_PREREQS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_CUSTOM_PREREQS_340.ldt FND_TABLE TABLE_NAME=XX_CUSTOM_PREREQS

echo 'Bajando objeto XX_XX_MAPPING_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxtables.lct XX_TBL_XX_MAPPING_VALUES_332.ldt FND_TABLE TABLE_NAME=XX_MAPPING_VALUES

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_213.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_HEADER1

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_214.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_HEADER2

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_215.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_HEADER3

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_216.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_HEADER4

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_207.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_HEADER5

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_217.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_ORDER_BY

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_212.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_RESULT

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_218.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_FROM1

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_219.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_FROM2

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_236.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_SELECT1

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_238.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_SELECT2

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_240.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_SELECT3

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_220.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE1

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_229.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE10

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_230.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE11

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_231.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE12

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_232.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE13

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_233.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE14

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_234.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE15

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_221.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE2

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_222.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE3

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_223.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE4

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_224.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE5

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_225.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE6

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_226.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE7

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_227.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE8

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_228.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_CSC_SQL_STATEMENT_WHERE9

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_209.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_DOWNLOAD_COMMAND

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_210.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_DOWNLOAD_DRIVER

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_211.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_DOWNLOAD_DRV_PARAM

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_208.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_DOWNLOAD_ENTITY

echo 'Bajando objeto XX_FND_FLEX_VALUES'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxflexfields.lct XX_DFF_FND_FLEX_VALUES_241.ldt DESC_FLEX DESCRIPTIVE_FLEXFIELD_NAME=FND_FLEX_VALUES DESCRIPTIVE_FLEX_CONTEXT_CODE='XX_CTRL_CUSTOMS' END_USER_COLUMN_NAME=XX_DOWNLOAD_ORDER_BY

echo 'Bajando objeto XX_XXCSCINF'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXCSCINF_292.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXCSCINF

echo 'Bajando objeto XX_XXDOCCUS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXDOCCUS_294.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXDOCCUS

echo 'Bajando objeto XX_XXDOWNLD'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXDOWNLD_290.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXDOWNLD

echo 'Bajando objeto XX_XXDRIVER'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXDRIVER_345.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXDRIVER

echo 'Bajando objeto XX_XXDRIVER'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXCUSCOP_346.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXCUSCOP

echo 'Bajando objeto XX_XXDRIVER'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXCUSVER_347.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXCUSVER

echo 'Bajando objeto XX_XXDRIVER'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxconcurrents.lct XX_CNC_XXCUSEXE_348.ldt PROGRAM CONCURRENT_PROGRAM_NAME=XXCUSEXE

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_292.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXCSCINF'

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_294.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXDOCCUS'

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_290.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXDOWNLD'

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_345.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXDRIVER'

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_346.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXCUSCOP'

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_347.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXCUSVER'

echo 'Bajando objeto XX_XX_ALL_REPORTS'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct XX_GRP_XX_ALL_REPORTS_348.ldt REQUEST_GROUP REQUEST_GROUP_NAME='XX All Reports' UNIT_TYPE=P UNIT_NAME='XXCUSEXE'

echo 'Bajando objeto XX_XX_MAIN_MENU'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxmenus.lct XX_MEN_XX_MAIN_MENU_300.ldt MENU  PARENT_MENU_NAME=XX_MAIN_MENU FUNCTION_NAME=XXFNDCUS

echo 'Bajando objeto XX_XX_MAIN_MENU'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxmenus.lct XX_MEN_XX_MAIN_MENU_304.ldt MENU  PARENT_MENU_NAME=XX_MAIN_MENU FUNCTION_NAME=XX_QUICKCODES

echo 'Bajando objeto XX_XX_MAIN_MENU'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxmenus.lct XX_MEN_XX_MAIN_MENU_302.ldt MENU  PARENT_MENU_NAME=XX_MAIN_MENU FUNCTION_NAME=XX_XXMAPVAL

echo 'Bajando objeto XX_XX_MAIN_MENU'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxmenus.lct XX_MEN_XX_MAIN_MENU_306.ldt MENU  PARENT_MENU_NAME=XX_MAIN_MENU SUB_MENU_NAME=FND_OTHER4.0

echo 'Bajando objeto XX_XX_CUSTOM_ENABLED_FLAG'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxprofiles.lct XX_PRF_XX_CUSTOM_ENABLED_FLAG_125.ldt PROFILE PROFILE_NAME=XX_CUSTOM_ENABLED_FLAG

echo 'Bajando objeto XX_XX_FND_FLAG'
FNDLOAD $APPS_USER/$APPS_PWD@$BASE  0 Y DOWNLOAD $XBOL_TOP/admin/XX/util/import/xxprofiles.lct XX_PRF_XX_FND_FLAG_120.ldt PROFILE PROFILE_NAME=XX_FND_FLAG
